import { Container, Headers } from '@/components'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Next Pizza | Корзина',
	description: 'Generated by create next app',
}

export default function CheckoutLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<main className='min-h-screen bg-[#F4F1EE]'>
			<Container>
				<Headers
					hasSearch={false}
					hasCart={false}
					className='border-b-gray-200'
				/>

				{children}
			</Container>
		</main>
	)
}
